package com.entity;

public class test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.DESCRIBE
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.VALUE
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.TIME_OF_VALUE
     *
     * @mbggenerated
     */
    private String timeOfValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.TYPE
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.ID
     *
     * @return the value of test.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.ID
     *
     * @param id the value for test.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.DESCRIBE
     *
     * @return the value of test.DESCRIBE
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.DESCRIBE
     *
     * @param describe the value for test.DESCRIBE
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.VALUE
     *
     * @return the value of test.VALUE
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.VALUE
     *
     * @param value the value for test.VALUE
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.UNIT
     *
     * @return the value of test.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.UNIT
     *
     * @param unit the value for test.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.TIME_OF_VALUE
     *
     * @return the value of test.TIME_OF_VALUE
     *
     * @mbggenerated
     */
    public String getTimeOfValue() {
        return timeOfValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.TIME_OF_VALUE
     *
     * @param timeOfValue the value for test.TIME_OF_VALUE
     *
     * @mbggenerated
     */
    public void setTimeOfValue(String timeOfValue) {
        this.timeOfValue = timeOfValue == null ? null : timeOfValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.TYPE
     *
     * @return the value of test.TYPE
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.TYPE
     *
     * @param type the value for test.TYPE
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }
}