/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rbac.controller.system;

import com.rbac.form.system.MailReceiveListForm;
import com.rbac.service.MailReceiveService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.util.List;

/**
 * MyEclipse Struts Creation date: 04-25-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/roleList" name="roleListForm"
 *                input="/system/roleList.jsp" scope="request" validate="true"
 */
@Controller
public class MailReceiveListController{

	@Autowired
	MailReceiveService mailReceiveService;

	@RequestMapping(value = "/mailReceiveList", method = RequestMethod.GET)
	public String ActionListRedirect(MailReceiveListForm mailReceiveListForm,HttpServletRequest request,HttpSession session){
		List mailReveiveList = mailReceiveService.getMailReceives(mailReceiveListForm.getMailNameQry(),mailReceiveListForm.getMailAddressQry());
		request.setAttribute("mailReceiveList", mailReveiveList);
		return "mailReceiveList";
	}

	@RequestMapping(value = "/mailReceiveList", method = RequestMethod.POST)
	public ModelAndView ActionListAction(MailReceiveListForm mailReceiveListForm,HttpServletRequest request,HttpSession session){
		ModelAndView model;
		List mailReveiveList = mailReceiveService.getMailReceives(mailReceiveListForm.getMailNameQry(), mailReceiveListForm.getMailAddressQry());
		//session.setAttribute("mailReceiveList","");
		model = new ModelAndView("mailReceiveList");
		model.addObject("mailReceiveList",mailReveiveList);
		return model;
	}
}