# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = test_db
DESTDIR = ../../../bin
QT += core sql xml xmlpatterns
CONFIG += debug console
DEFINES += WIN64 QT_DLL QT_SQL_LIB QT_XML_LIB QT_XMLPATTERNS_LIB DBAPI_LIB
INCLUDEPATH += . \
    ./GeneratedFiles/Debug \
    ../../../dbapi
LIBS += -L"./../../../lib" \
    -ldbapi -llibmysqld
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
SOURCES += ./main.cpp
