/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rbac.form.system;



/**
 * MyEclipse Struts
 * Creation date: 04-25-2014
 * 
 * XDoclet definition:
 * @struts.form name="roleListForm"
 */
public class MailReceiveListForm{

	private String mailNameQry;

	public String getMailNameQry() {
		return mailNameQry;
	}

	public void setMailNameQry(String mailNameQry) {
		this.mailNameQry = mailNameQry;
	}

	public String getMailAddressQry() {
		return mailAddressQry;
	}

	public void setMailAddressQry(String mailAddressQry) {
		this.mailAddressQry = mailAddressQry;
	}

	public String getQuery() {
		return query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getDel() {
		return del;
	}

	public void setDel(String del) {
		this.del = del;
	}

	private String mailAddressQry;


	private String query;
	
	private String del;

	public String getDeleteIds() {
		return deleteIds;
	}

	public void setDeleteIds(String deleteIds) {
		this.deleteIds = deleteIds;
	}

	private String deleteIds;

//	/**
//	 * Method validate
//	 * @param mapping
//	 * @param request
//	 * @return ActionErrors
//	 */
//	public ActionErrors validate(ActionMapping mapping,
//			HttpServletRequest request) {
//		// TODO Auto-generated method stub
//		return null;
//	}
//
//	/**
//	 * Method reset
//	 * @param mapping
//	 * @param request
//	 */
//	public void reset(ActionMapping mapping, HttpServletRequest request) {
//		// TODO Auto-generated method stub
//		this.query = null;
//	}
}